"""Render a compatibility matrix (markdown) from dataset cards."""

GENERATED_NOTE = (
    "<!-- Generated from dataset_cards/*.yaml and configs/matrices/{modality}.yaml "
    "by scripts/build_matrices.py. Edit the cards, not this file. -->"
)


def _table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return lines


def render_matrix(cards, spec):
    columns = [cards[c.id] for c in spec.columns]
    lines = [GENERATED_NOTE.format(modality=spec.modality), "", spec.preamble.rstrip(), ""]
    lines += _table(
        ["Parameter"] + [c.label for c in spec.columns],
        [[f"**{row.label}**"] + [card.facts[row.key].text for card in columns] for row in spec.rows],
    )
    for supplement in spec.supplements:
        card = cards[supplement.id]
        lines += ["", f"## {supplement.heading}", ""]
        lines += _table(["Parameter", "Value"], [[label, fact.text] for label, fact in card.supplementary.items()])
    if spec.cross_dataset:
        lines += ["", f"## {spec.cross_dataset_heading or 'Cross-dataset facts'}", ""]
        lines += _table(["Parameter", "Value"], [[label, fact.text] for label, fact in spec.cross_dataset.items()])
    return "\n".join(lines) + "\n"


def render_ungraded(cards, specs):
    """Worklist of UNGRADED cells: where each one lives and what it says."""
    lines = [
        "<!-- Generated by scripts/build_matrices.py. Grade cells in the cards; this list shrinks. -->",
        "",
        "# Ungraded matrix cells",
        "",
        "Cells carried over from the hand-written matrices without an evidence marker.",
        "Each lives in `dataset_cards/<dataset>.yaml` under `facts:` (or `supplementary:`) at the key shown.",
        "Grade one by setting its `status` (and `n` for EMPIRICAL) after checking the source.",
    ]
    labels = {row.key: row.label for spec in specs for row in spec.rows}
    for card in cards.values():
        cells = [("facts", key, labels.get(key, key), fact) for key, fact in card.facts.items()]
        cells += [("supplementary", key, key, fact) for key, fact in card.supplementary.items()]
        cells = [c for c in cells if c[3].status == "UNGRADED"]
        if not cells:
            continue
        lines += ["", f"## {card.name} — {len(cells)} cells (`dataset_cards/{card.id}.yaml`)", ""]
        lines += _table(["Section", "Key", "Row", "Text"],
                        [[section, f"`{key}`", label, fact.text] for section, key, label, fact in cells])
    return "\n".join(lines) + "\n"


def status_counts(cards, spec):
    """{dataset id: {status: number of matrix cells}} for the evidence report."""
    counts = {}
    for column in spec.columns:
        tally = {}
        for row in spec.rows:
            status = cards[column.id].facts[row.key].status
            tally[status] = tally.get(status, 0) + 1
        counts[column.id] = tally
    return counts
