"""Render the compatibility matrices and the evidence audit from cards and roles."""

GENERATED_NOTE = (
    "<!-- Generated from dataset_cards/*.yaml, configs/dataset_roles.yaml and "
    "configs/matrices/{modality}.yaml by scripts/build_matrices.py. Edit those, not this file. -->"
)
STATUS_ORDER = ["VERIFIED", "EMPIRICAL", "AUTHOR_DOC", "AUTHOR_CODE", "REPO_METADATA", "INFERRED",
                "CONFLICTING", "UNKNOWN", "NOT_APPLICABLE", "UNGRADED"]


def _table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return lines


def _cell(card, roles, row):
    return roles[card.id].rows[row.key].text if row.policy else card.facts[row.key].text


def render_matrix(cards, roles, spec):
    columns = [cards[c.id] for c in spec.columns]
    lines = [GENERATED_NOTE.format(modality=spec.modality), "", spec.preamble.rstrip(), ""]
    lines += _table(
        ["Parameter"] + [c.label for c in spec.columns],
        [[f"**{row.label}**"] + [_cell(card, roles, row) for card in columns] for row in spec.rows],
    )
    for supplement in spec.supplements:
        card = cards[supplement.id]
        rows = [[label, fact.text] for label, fact in card.supplementary.items()]
        if card.id in roles:
            rows += [[label, policy.text] for label, policy in roles[card.id].supplementary.items()]
        lines += ["", f"## {supplement.heading}", ""] + _table(["Parameter", "Value"], rows)
    if spec.cross_dataset:
        lines += ["", f"## {spec.cross_dataset_heading or 'Cross-dataset facts'}", ""]
        lines += _table(["Parameter", "Value"], [[label, fact.text] for label, fact in spec.cross_dataset.items()])
    return "\n".join(lines) + "\n"


def iter_claims(cards, specs):
    """(dataset id, section, key, label, claim) for every graded claim in cards and specs."""
    labels = {row.key: row.label for spec in specs for row in spec.rows}
    for card in cards.values():
        for key, fact in card.structure:
            yield card.id, "structure", key, key, fact
        for key, measured in card.signal:
            yield card.id, "signal", key, key, measured
        for key, fact in card.facts.items():
            yield card.id, "facts", key, labels.get(key, key), fact
        for key, fact in card.supplementary.items():
            yield card.id, "supplementary", key, key, fact
    for spec in specs:
        for key, fact in spec.cross_dataset.items():
            yield f"cross-dataset ({spec.modality})", "cross_dataset", key, key, fact


def render_audit(cards, specs):
    claims = list(iter_claims(cards, specs))
    lines = [
        "<!-- Generated by scripts/build_matrices.py from the cards. Do not edit. -->",
        "",
        "# Evidence audit",
        "",
        "Every claim in the dataset cards (structure, typed signal fields, matrix facts, supplementary rows)",
        "by evidence status. Status meanings and grading rules: `src/droneacharya/cards/schema.py`.",
        "Project decisions are not claims; they live in `configs/dataset_roles.yaml`.",
        "",
        "## Summary",
        "",
    ]
    datasets = list(dict.fromkeys(c[0] for c in claims))
    counts = {d: {} for d in datasets}
    for dataset, *_, claim in claims:
        counts[dataset][claim.status] = counts[dataset].get(claim.status, 0) + 1
    used = [s for s in STATUS_ORDER if any(s in t for t in counts.values())]
    rows = [[d] + [str(counts[d].get(s, 0)) for s in used] + [str(sum(counts[d].values()))] for d in datasets]
    totals = [str(sum(counts[d].get(s, 0) for d in datasets)) for s in used]
    rows.append(["**total**"] + [f"**{t}**" for t in totals] + [f"**{len(claims)}**"])
    lines += _table(["Dataset"] + used + ["claims"], rows)

    kinds = {}
    for *_, claim in claims:
        kind = getattr(claim, "kind", "FACT")
        kinds[kind] = kinds.get(kind, 0) + 1
    lines += ["", "Kinds: " + ", ".join(f"{k} {v}" for k, v in sorted(kinds.items())), ""]

    for status, title in (("UNGRADED", "Ungraded"), ("CONFLICTING", "Conflicting"), ("UNKNOWN", "Unknown")):
        selected = [c for c in claims if c[4].status == status]
        lines += [f"## {title} ({len(selected)})", ""]
        if not selected:
            lines += ["None.", ""]
            continue
        table = []
        for dataset, section, key, label, claim in selected:
            text = getattr(claim, "text", None) or getattr(claim, "note", None) or ""
            if claim.conflict:
                text += " — " + "; ".join(f"{c.status}: {c.claim} ({c.source})" for c in claim.conflict)
            table.append([dataset, section, f"`{key}`", text.replace("|", "\\|")])
        lines += _table(["Dataset", "Section", "Key", "Claim"], table) + [""]
    return "\n".join(lines).rstrip() + "\n"


def status_counts(cards, spec):
    """{dataset id: {status: number of card cells}} for one matrix."""
    counts = {}
    for column in spec.columns:
        tally = {}
        for row in spec.rows:
            if row.policy:
                continue
            status = cards[column.id].facts[row.key].status
            tally[status] = tally.get(status, 0) + 1
        counts[column.id] = tally
    return counts
